name: Recipe App API
on: [push]

jobs:
  Check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint
        uses: rickstaa/action-black@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: flake8 Lint
        uses: py-actions/flake8@v2
      - name: Run tests
        run: |
          python manage.py test
