name: Recipe App API
on: [push]

jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker Compose Up
        run: |
          docker-compose up
      - name: Run Django Tests
        run: |
          docker-compose run app sh -c "python manage.py test"
      - name: Refactor
        run: |
          docker-compose run app sh -c "black ."