name: Recipe App API
on: [push]

jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Run tests with Docker and refactor
        run: |
          docker-compose run app sh -c "python manage.py wait_for_db && python manage.py test && black . "